### ISSUE TITLE
Playback problems.

### ISSUE THREAD

**Issue by Noemata** [kakone/VLC.MediaElement#10] opened 2017-02-22 01:55 UTC
The good:

- playback quality appears better than the built in equivalent of MediaElement's codecs, which is surprising
- CPU utilization if very very good, in some cases noticeably better than the built in MediaElement
- the command and control interface has interesting use scenarios (provided more of it was exposed)
- range of supported file types is fantastic

The bad:

- video scrub operations do not always work (the player gets stuck)
- when you scrub the video the "..." loading indicator starts to cycle when it should stop after you have stopped scrubbing while paused
- repeatedly loading the same video takes progressively longer ??
- logging is very verbose and laggy (logging should be off by default)
- loading a file from the file system has a significant start time delay that is much longer than the built in MediaElement, which is the single biggest limitation in my view

Streaming from the file system should be faster than from a URL and not the reverse.  There must be a more efficient way of starting playback from a file.

**Comment by kakone** [comment] 2017-02-22 20:35
> video scrub operations do not always work (the player gets stuck)

It's a bug in libVLC, I can't do nothing for that. If you can reproduce the problem in VLC for UWP, you can create a new issue [here](https://code.videolan.org/videolan/vlc-winrt/issues/new).
I see there is [an identical issue](https://code.videolan.org/videolan/vlc-winrt/issues/146) in the bug tracker.

> when you scrub the video the "..." loading indicator starts to cycle when it should stop after you have stopped scrubbing while paused

It will be fixed in version [0.9.11](https://www.nuget.org/packages/VLC.MediaElement/0.9.11).

> repeatedly loading the same video takes progressively longer ??

I couldn't reproduce this problem.

> logging is very verbose and laggy (logging should be off by default)

Why is it laggy ? If you use the NuGet package, there is no information in output window and the log file is only saved if an error is encountered.

> loading a file from the file system has a significant start time delay that is much longer than the built in MediaElement, which is the single biggest limitation in my view

I don't manage the file access, all is done in libVLC. On my computer, I didn't notice a difference compared to the classic MediaElement (but, I have a SSD).

**Closed** 2017-06-25 20:55 UTC
Labels: bug, enhancement
